
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSOC COMMA DECLARE EQUALS ID LBRACKET LPAREN NUMBER RBRACKET RPARENarray_initialize : DECLARE ASSOC ID EQUALS LPAREN array_elements RPARENarray_elements : array_assignment\n                      | array_elements array_assignmentarray_assignment : LBRACKET array_index RBRACKET EQUALS valuearray_index : NUMBER COMMA NUMBERvalue : ID\n             | NUMBER'
    
_lr_action_items = {'DECLARE':([0,],[2,]),'$end':([1,10,],[0,-1,]),'ASSOC':([2,],[3,]),'ID':([3,16,],[4,19,]),'EQUALS':([4,14,],[5,16,]),'LPAREN':([5,],[6,]),'LBRACKET':([6,7,8,11,18,19,20,],[9,9,-2,-3,-4,-6,-7,]),'RPAREN':([7,8,11,18,19,20,],[10,-2,-3,-4,-6,-7,]),'NUMBER':([9,15,16,],[13,17,20,]),'RBRACKET':([12,17,],[14,-5,]),'COMMA':([13,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'array_initialize':([0,],[1,]),'array_elements':([6,],[7,]),'array_assignment':([6,7,],[8,11,]),'array_index':([9,],[12,]),'value':([16,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> array_initialize","S'",1,None,None,None),
  ('array_initialize -> DECLARE ASSOC ID EQUALS LPAREN array_elements RPAREN','array_initialize',7,'p_array_initialize','2darrayinit.py',57),
  ('array_elements -> array_assignment','array_elements',1,'p_array_elements','2darrayinit.py',61),
  ('array_elements -> array_elements array_assignment','array_elements',2,'p_array_elements','2darrayinit.py',62),
  ('array_assignment -> LBRACKET array_index RBRACKET EQUALS value','array_assignment',5,'p_array_assignment','2darrayinit.py',65),
  ('array_index -> NUMBER COMMA NUMBER','array_index',3,'p_array_index','2darrayinit.py',68),
  ('value -> ID','value',1,'p_value','2darrayinit.py',71),
  ('value -> NUMBER','value',1,'p_value','2darrayinit.py',72),
]
